# Generated by Django 3.2.8 on 2021-10-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_color_color_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='description',
            field=models.CharField(default='Describe Color', max_length=100),
        ),
    ]
